baseurl = "/"
languageCode = "en-us"
title = "Josh Brandoff"
theme = "hugo-strata-theme"
disqusShortname = "brandoff"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Josh Brandoff"
	description = "polyglot engineer, leader, product owner, and systems architect"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Polyglot engineer, leader, product owner, and systems architect with a 10+ year track record of success at transformative startups in the *healthcare*, *AI*, *cryptocurrency*, and *nonprofit* industries"
		# The icons will be shown if you enter your username
		twitter = "jbrandoff"
		github = "emergentbehavior"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://linkedin.com/in/brandoff"

		copyright = [
			"&copy; 2021 Josh Brandoff"
		]


	[params.about]
		hide  = false
		title = "about"
                content = "I'm a seasoned engineer, technology leader, and architect who uses technology to bring visions to life. "
    content = "I'm presently Head of Data at [Reify Health](https://reifyhealth.com), where we are building solutions to connect and empower the global *clinical trial ecosystem*. I co-founded and was CTO at [Wade & Wendy](https://wadeandwendy.ai), a *conversational AI* company which provides a personal career guide to candidates and automation technology to talent acquisition partners. I was an early Core Developer and whitepaper author at [Storj](storj.io), a *decentralized* cloud storage network using *Ethereum*, and Lead Developer at [Harmony Labs](https://harmonylabs.org), where we used *data science* to measure and support the positive impact of *media systems* on society. Additionally, I was the founding technologist at the award-winning [National Museum of Mathematics](https://momath.org) in NYC.<br><br> I'm deeply interested in **complex systems science**, **emergent behavior**, and **distributed** or **decentralized systems** and have [published work](http://link.springer.com/chapter/10.1007%2F978-3-642-20760-0_4) on genetic stigmergy, a **biologically-inspired algorithm** that supports **self-organization** of robotic swarms. My interest in biologically-inspired systems also led me to study **permaculture** design  with [Andrew Faust](http://www.permaculturenewyork.com/).<br/><br/>My programming languages of choice are **Clojure**, **ClojureScript**, **Golang**, **Python**, and **JavaScript**. I'm also fluent with **Linux**, **AWS**, and **GCP**.<br/><br/>I fervently enjoy *karaoke*, *swimming*, *running*, and making my daughters *laugh*."

	[params.portfolio]
		hide  = false
		title = "selected demos"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
      vid = "ytt28dU_92E"
			title = "Storj: Decentralized Cloud Storage"
			description = "Presented Storj at [Hedgeable](https://www.hedgeable.com/)'s 'Bitcoin: No Boundaries' event in NYC."

		[[params.portfolio.gallery]]
      vid = "lFuflBdpAnE"
			title = "Storj: DriveShare"
			description = "Walkthrough of Storj's DriveShare software and my monitoring dashboard."

		[[params.portfolio.gallery]]
      vid = "JmN2BzXPeH0"
			title = "Aavya Health: NutriCart"
			description = "Kiosk-based adaptive shopping cart that recommends products and services based on your health situation. "

		[[params.portfolio.gallery]]
      vid = "n-DBx1HTUtk"
			title = "Acquatic Swarm 'Immune System'"
			description = "Simulation of acquatic swarming robots using quorum sensing to detect contanimants and collectively notify human oversight."

    [[params.portfolio.gallery]]
      vid = "Kwq8KFeUf8g"
      title = "Autonomous Swarm Robots Mapping Home"
      description = "A simulated swarm of three dozen autonomous robots explore and map a complex home environment."

		[[params.portfolio.gallery]]
      vid = "bQ67952nlvo"
			title = "Evolution of Swarm Exploration Algorithms"
			description = "Simplified visualization of a swarm of robots evolving strategies to explore an unknown map in real-time."

		[[params.portfolio.gallery]]
      vid = "FVBrzJag6XI"
			title = "MoMath: This is the Tetraxis!"
			description = "Created music and contributed vocals for promotional 'This is the Tetraxis!' video. :)"

	[params.recentposts]
		hide  = false
		title = "recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "blog"
	url  = "post/"
	weight = 10

[[menu.main]]
  name = "gpg"
  url = "https://brandoff.is/gpg/2E02E9F001103FC5"
  weight = 20

